apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-http-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: torqueloggerdynamodb
spec:
  hosts:
  - yamini.msvd.party
  gateways:
  - istio-http-gateway
  http:
  - match:
    - uri:
        prefix: /torqueloggerdynamodb
    rewrite:
      uri: /logs
    route:
    - destination:
        host: torqueloggerdynamodb
        port:
          number: 4000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: torqueloggerdynamodb
spec:
  host: torqueloggerdynamodb
  subsets:
  - name: v1
    labels:
      version: v1
